services:
  postgres:
    image: postgres:15-alpine
    container_name: currency-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_USER: currency_user
      POSTGRES_PASSWORD: currency_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U currency_user -d currency_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: