spring:
  application:
    name: currency-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/currency_db
    username: currency_user
    password: currency_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        schema_validation: false
        hbm2ddl:
          auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

# External API configuration
openexchangerates:
  api:
    url: https://openexchangerates.org/api
    app-id: f5d35ca994d94d3691fe4cd1bcea81b1

# Logging
logging:
  level:
    com.jack.currency: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

# Server configuration
server:
  port: 9090

# Swagger UI path
springdoc:
  swagger-ui:
    path: /swagger-ui.html